{
	"version": 1732271182,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/desaingamekhansa-sheet0.png",
		"images/pngtransparentbuttonarrowbuttonblueangletrademarkremovebgpreview-sheet0.png",
		"images/imagesremovebgpreview-sheet0.png",
		"images/desaingamekhansa2-sheet0.png",
		"images/desaingamekhansa3-sheet0.png",
		"images/desaingamekhansa4-sheet0.png",
		"images/tiledbackground.png",
		"images/desaingamekhansa6-sheet0.png",
		"images/desaingamekhansa7-sheet0.png",
		"images/replay_removebgpreview-sheet0.png",
		"images/home_removebgpreview-sheet0.png",
		"images/replay-sheet0.png",
		"images/home-sheet0.png",
		"images/home3-sheet0.png",
		"images/home_removebgpreview2-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"media/lagu game.m4a",
		"media/lagu game.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"banksoal.txt"
	]
}